version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - initializing build
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running test...
      - npm run test
      - echo Running eslint...
      - npm run eslint
  post_build:
    commands:
      - echo Build completed on `date`
